stages:
  - build
  - deploy

build:
  stage: build
  image: maven:3.8-openjdk-17
  script:
    - mvn clean package
    - ls target
  only:
    - merge_requests
    - main
    - dev
    - ci
  artifacts:
    name: "eq9-appliance-plugin"
    paths:
      - target/*.jar
publish:
  image: docker:dind
  stage: deploy
  services:
    - docker:dind
  script:
    - if [ "$CI_COMMIT_BRANCH" == "main" ]; then TAG="latest"; else TAG="$CI_COMMIT_BRANCH"; fi
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/$CI_PROJECT_PATH:${TAG} .
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH:${TAG}
  only:
    - dev
    - main
    - ci


